layout_spectrum: 0.26317722442790425
typography_spectrum: 0.7681510770867699
color:
  brandStrength: 0.5694362248431449
  lightness: 0.6147572894750328
  saturation: 0.3228328793907151
  rhythmicContrast: 0.7898013620095162
  brandColors:
    - '#000000'
    - '#3E4E86'
    - '#A371C8'
    - '#DBEAFE'
    - '#CEA9DD'
github: true
analytics:
  google: UA-45947854-4
author:
  name: Hector Mejia
  email: hectorjaime.mejia@gmail.com
  url: hmejia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/57bfc3a0-a348-4b38-8062-6084c44cc6b3.png
name: hmejia
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/930fd71f-a9cf-4d86-b9c8-49ee816efbcf.png
title: Hector Mejia
content: []
description: Interaction Researcher
purpose:
  - type: contact
    url: 'mailto:hectorjaime.mejia@gmail.com'
    label: Contact me
