typography_spectrum: 0.9888239747611345
color:
  brandStrength: 0.9798943678768223
  lightness: 0.14939919315693478
  saturation: 0.10782291525928765
  rhythmicContrast: 0.5492231693128954
  brandColors:
    - '#000000'
    - '#3E4E86'
    - '#A371C8'
    - '#DBEAFE'
    - '#CEA9DD'
github: true
layout_spectrum: 0.17537724371095845
analytics:
  google: UA-45947854-4
author:
  name: Hector Mejia
  email: hectorjaime.mejia@gmail.com
  url: hmejia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/57bfc3a0-a348-4b38-8062-6084c44cc6b3.png
name: hmejia
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/930fd71f-a9cf-4d86-b9c8-49ee816efbcf.png
title: Hector Mejia
content: []
description: Interaction Researcher
purpose:
  - type: contact
    url: 'mailto:hectorjaime.mejia@gmail.com'
    label: Contact me
