layout_spectrum: 0.6302983991877351
typography_spectrum: 0.5063421343093609
color:
  brandStrength: 0.25254796237666344
  lightness: 0.891371031299713
  saturation: 0.9325937917508591
  rhythmicContrast: 0.4157466705929082
  brandColors:
    - '#000000'
    - '#3E4E86'
    - '#A371C8'
    - '#DBEAFE'
    - '#CEA9DD'
github: true
analytics:
  google: UA-45947854-4
author:
  name: Hector Mejia
  email: hectorjaime.mejia@gmail.com
  url: hmejia.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/57bfc3a0-a348-4b38-8062-6084c44cc6b3.png
name: hmejia
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/930fd71f-a9cf-4d86-b9c8-49ee816efbcf.png
title: Hector Mejia
content: []
description: Interaction Researcher
purpose:
  - type: contact
    url: 'mailto:hectorjaime.mejia@gmail.com'
    label: Contact me
